### ISSUE TITLE
[Suggestion]: Catppuccin theme

### ISSUE THREAD

**Issue by Pocco81** [mattleong/CosmicNvim#16]
First off, awesome vimdistro (came from the Reddt post), I'm actually porting stuff from it to my personal config, so great job! Very well structured indeed.

So, since the theme of the distro is space (assuming from the name) I thought you might like a colorscheme of mine called [Katppuccino](https://github.com/Pocco81/Catppuccino.nvim/issues/44#issuecomment-954424799), which goes more inline IMO.

Again, awesome distro! since this is just a suggestion about something that is still under development feel free to close the issue :)

**Comment by mattleong** [comment]
Hi @Pocco81! Thanks for reaching out!

I'm definitely not completely against this.. I've seen your OG Catppuccino theme around and really liked it. And I have been wanting to try something new after using Tokyonight for so long (it's just so pretty 😭). 

Let me play around with the remastered version and I'll get back to you 🙂

**Comment by Pocco81** [comment]
I haven't updated the doc yet on that branch, it's basically the same as it was before but with minor changes. I'll do that as soon as possible.

But yeah, I guess that for now you'll have to guess how to configure it lol. Let me know if you need help with that.

**Comment by mattleong** [comment]
@Pocco81 😎

https://github.com/mattleong/CosmicNvim/issues/23#issuecomment-966810302

**Comment by Pocco81** [comment]
Hey @mattleong! I will be releasing [Catppuccin today](https://github.com/catppuccin). The [color palette](https://github.com/catppuccin/catppuccin) it self is ready. The only thing that's not ready yet is the [nvim theme](https://github.com/catppuccin/nvim), which I'll be working on today.

**Comment by mattleong** [comment]
@Pocco81 Awesome! Let me know and I'll switch off `dev-remaster` and move to the new repo.
