### ISSUE TITLE
Extra plugins nvim-treesitter

### ISSUE THREAD

**Issue by carlosrivas2021** [mattleong/CosmicNvim#17]
Hello,

I have problems with the extra plugins:
'windwp/nvim-ts-autotag'
'nvim-treesitter/nvim-treesitter-refactor'

These give me errors "Failed to install" I'm using nvim v0.6.0

These are for nvim version o has other reason?

Thanks
![Screenshot_20211103_153846](https://user-images.githubusercontent.com/17257366/140180821-96930869-035d-456c-ab59-0ab2ebc385aa.png)

![Screenshot_20211103_153940](https://user-images.githubusercontent.com/17257366/140180948-4a3b07f7-5431-428b-92bd-bfb402615631.png)

**Comment by mattleong** [comment]
Hi @carlosrivas2021, thank you for the report!

I just pushed a fix for this a few hours ago thanks to another user reporting this earlier. Will you make sure to pull down the latest and try rerunning?

**Comment by carlosrivas2021** [comment]
Hi @mattleong, thank you for your answer.

I cloned your repo again, but I'm having the same error. I checked the version and I have the latest.

![Screenshot_20211103_174357](https://user-images.githubusercontent.com/17257366/140197275-3137bd4c-796d-4d3b-9d4c-d5cc4c079e50.png)

**Comment by mattleong** [comment]
@carlosrivas2021 Did you already run `:PackerCompile` again?

**Comment by carlosrivas2021** [comment]
@mattleong thanks, yes, I think I was not cleaning good Packer.

Can I install copilot github without problem or I have to disable any plugin?

**Comment by mattleong** [comment]
@carlosrivas2021 Great to hear! I'll close this ticket then.

You _should_ be able to install copilot with no issues, although I haven't tried myself. If you run into problems with it, feel free to post another issue!

Thanks!
