### ISSUE TITLE
Is there any way to config the new color theme instead of tokyonight

### ISSUE THREAD

**Issue by SzelamC** [mattleong/CosmicNvim#18]
I am new at lua and i love tokyonight very much, but i want to try some other theme.
Is there any way to add new theme? I appreciate your help very much!!!

**Comment by mattleong** [comment]
Yes, you can! Take a look [here](https://github.com/mattleong/CosmicNvim/blob/main/lua/cosmic/config/plugins.lua#L24)

However, by doing so, you will also disable the statusline, so you will also need to readd that yourself.
