### ISSUE TITLE
current build appears to be broken

### ISSUE THREAD

**Issue by undeadbydawn** [mattleong/CosmicNvim#19]
getting a load of errors on nvim keybinds
packer.nvim: Error running config for nvim-cmp:.. lsp/autocomplete.lua:5: module
no field package.preload['luasnip']Stale cache
and a load of
no file

previous build (which I have backed up) works perfectly

**Comment by undeadbydawn** [comment]
Error on relaunch trying [space]ff: .config/nvim/lua/cosmic/lsp/autocomplete/lua:77: module 'lspkind' not found
no field package.preload['lspkind']Stale cache
no file './lspkind.lua'
etc

**Comment by mattleong** [comment]
Have you already tried running `:PackerSync`?

**Comment by undeadbydawn** [comment]
yup. Several times.
I've also done multiple clean installs just to be absolutely sure it's not an error on my end

**Comment by mattleong** [comment]
Gotcha. Will look at this asap!

**Comment by mattleong** [comment]
@undeadbydawn Latest updates should fix those issues! Please let me know if you get the chance.

Thank you so much for the report!

**Comment by undeadbydawn** [comment]
Perfect. Works just fine. Cheers!
