### ISSUE TITLE
Error running config for nvim-lsp-installer

### ISSUE THREAD

**Issue by giluis** [mattleong/CosmicNvim#20]
Hey!
This project is fantastic, you did an amazing job! I really like it. 
Almost everything works wonderfully, except for this
![image](https://user-images.githubusercontent.com/52404649/140822082-f10e6389-8445-4c16-b4cc-ee96a7e5e85a.png)
I haven't made any changes anywhere in the config, and have tried deleting and cloning again, and get this same error.

To reproduce:
```bash 
git clone https://github.com/mattleong/CosmicNvim.git nvim
nvim ./nvim/lua/cosmic/init.lua
```
Then I get this error:
![image](https://user-images.githubusercontent.com/52404649/140822830-283cac56-f39f-4152-9cf6-bec06808278e.png)

After some research, I found the answer (on issue #1 ): 
I just comment the 'cosmic.compiled' module on line 4.
After that I run `PackerCompile` and then `PackerInstall` and uncommented line 4

And then I get the error I mentioned in the beginning. Besides the error, I actually get error detection in lua (not in typescript) 

What can I do to solve this?

**Comment by mattleong** [comment]
What version of neovim are you running?

**Comment by giluis** [comment]
![image](https://user-images.githubusercontent.com/52404649/140981655-83c138c3-112e-4f96-bf58-86bd23d0baaa.png)
This is the result of running `nvim --version`

I have since downloaded the 0.6 appimage from the official repo and everything seems to be working!
However, in ./init.lua there is the following line:
![image](https://user-images.githubusercontent.com/52404649/140984103-50024c72-f48b-4538-b03e-04b4b0cbc3b8.png)

When I was statring CosmicNvim with the wrong version, I did not receive this error.

**Comment by mattleong** [comment]
@giluis Ahh thank you! Just fixed that.

Glad it's working for you now!
