### ISSUE TITLE
Total system freeze

### ISSUE THREAD

**Issue by undeadbydawn** [mattleong/CosmicNvim#21]
Extreme weirdness.
I've just had two total system freezes (not crashes. My system just _stops_ and needs hard reset) while searching for documents in Cosmic. This has never happened before and is not fun.

**Comment by mattleong** [comment]
Hm, very strange! 🤔

What command/mapping are you hitting exactly when that happens?

**Comment by undeadbydawn** [comment]
[space]ff
then searching for nvimrc
not sure if it was that file both times, but it was definitely find file. Haven't tried again since the second freeze.
Currently wondering if it's cos I'm using a fully tickless kernel, but this is the only scenario where I've had the problem - never mind twice

**Comment by mattleong** [comment]
Hmm.. by default, Telescope uses `fd` under the hood for `:Telescope find_files`, [here](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/files.lua#L170)

My guess is that this is more of a system issue than Cosmic. Happy to help how I can however!

**Comment by undeadbydawn** [comment]
yeah, just looking through the lua files and noticed the same. I may recompile as tickless idle tomorrow & try again.
Meanwhile, what would be the ideal way to add 'set wrap linebreak', since Cosmic isn't actually reading my .vimrc? (or at least doesn't appear to be)

**Comment by mattleong** [comment]
You can add it in by adding the file `config/editor.lua` and doing whatever you need there. There are examples in `config/examples` as well

**Comment by mattleong** [comment]
Specifically, you would put, `vim.o.wrap = true`

**Comment by undeadbydawn** [comment]
Excellent. Done, that's perfect

**Comment by undeadbydawn** [comment]
OK, no freezing with mainline kernel. I'll assume this issue is 100% local for now and get back if it happens again.

**Comment by mattleong** [comment]
Good to hear! And sounds great. Closing this for now :)
