### ISSUE TITLE
More colour scheme options

### ISSUE THREAD

**Issue by hsheikhali1** [mattleong/CosmicNvim#23]
As a web developer that use typescript often, I love this super simple and lightweight config.

I feel like the next evolution of this would include an option to select different colour schemes.

Some theme ideas:
Nord
One Dark
One Light
Doom
Molokai
Material
Github-nvim

The above could be a lot of work to implement given that you are also setting some highlighting but being able to select more than 1 colour scheme would be amazing!! Or at least have a guide to override/add our own.

**Comment by mattleong** [comment]
Thank you!

I'm already one step ahead of you :) I'm currently in the process of implementing a few first-class themes, in fact I already have the first one other than Tokyonight set up. 

I will leave this PR open so that others can see what's coming! 😄

**Comment by mattleong** [comment]
I'll take your suggestions into account as well. Nord is definitely on the list, I used it for years before Tokyonight!

**Comment by hsheikhali1** [comment]
Awesome! Love it - another thing that would be cool is having a table in the README for are the base commands. I took a quick peek and I only tweaked a few things but everything else is nice!

**Comment by mattleong** [comment]
@hsheikhali1 Which base commands are you referring to?

**Comment by mattleong** [comment]
https://github.com/mattleong/CosmicNvim/issues/25
