### ISSUE TITLE
[Suggestion]: Add indent-blankline.nvim

### ISSUE THREAD

**Issue by hsheikhali1** [mattleong/CosmicNvim#24]
So, I recently tweaked my config to have indent-blankline instead and it looks glorious. I was wondering if we can add this as the default rather than the list stuff we have currently. Or at least make it easier to toggle?

**Comment by mattleong** [comment]
Honestly, the amount of plugins is already getting close to it's limit. I'm going to be very strict on the reasoning for adding in a default plugin.

TBH, I'm not sure that it's worth adding in indent-blankline when it's so easy to add yourself via `config/plugins`.

**Comment by hsheikhali1** [comment]
After really thinking about it I think you're absolutely right. Given that you've made it near dead simple to add your own plugins we can just omit this ask
