### ISSUE TITLE
How to add lsp support of other languages?

### ISSUE THREAD

**Issue by giluis** [mattleong/CosmicNvim#27]
Hey, been using cosmic for about a week now, how can I add lsp support of other languages besides ts, js css, html etc.

Thanks

**Comment by undeadbydawn** [comment]
instructions are tucked away [here](https://github.com/mattleong/CosmicNvim/wiki/Installing-LSP-servers)

the main command you need is `:LspInstallInfo`

**Comment by mattleong** [comment]
@giluis check out the wiki link and let me know if you have more questions!
